// <auto-generated />
namespace DojoAcademia.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class turno1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(turno1));
        
        string IMigrationMetadata.Id
        {
            get { return "202108092214297_turno1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
